source 'http://rubygems.org'

gem 'sass', '~>3.3'
gem 'compass', '~>1.0'
gem 'breakpoint', '~>2.4'
gem 'singularitygs', '~>1.4'
gem 'toolkit', '~>2.0'
gem 'modular-scale', '~>2.0'
gem 'normalize-scss', '~>3.0'